baseURL = "https://jabdy.com/"
languageCode = "en-us"
title = "James Abdy"
enableRobotsTXT = true
[params]
  description = "Software, side projects, and occasional follow-through. James Abdy’s project notebook."
  author = "James Abdy"
[taxonomies]
  tag = "tags"
[permalinks]
  post = "/:year/:month/:day/:filename/"
[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  style = "github"
  lineNos = false
